query getContracts($from: String, $to: String, $limit: Int, $after: Int){
          Contract(filter: {lastUpdateDate: [$from, $to]}, limit: $limit, after: $after) {
            id
            parent_id: parentId
            root_id: rootId
            trd_buy_id: trdBuyId
            trd_buy_number_anno: trdBuyNumberAnno
            trd_buy_name_ru: trdBuyNameRu
            trd_buy_name_kz: trdBuyNameKz
            ref_contract_status_id: refContractStatusId
            deleted
            crdate
            last_update_date: lastUpdateDate
            supplier_id: supplierId
            supplier_biin: supplierBiin
            supplier_bik: supplierBik
            supplier_iik: supplierIik
            supplier_bank_name_kz: supplierBankNameKz
            supplier_bank_name_ru: supplierBankNameRu
            supplier_legal_address: supplierLegalAddress
            supplier_bill_id: supplierBillId
            contract_number: contractNumber
            sign_reason_doc_name: signReasonDocName
            sign_reason_doc_date: signReasonDocDate
            trd_buy_itogi_date_public: trdBuyItogiDatePublic
            customer_id: customerId
            customer_bin: customerBin
            customer_bik: customerBik
            customer_iik: customerIik
            customer_bill_id: customerBillId
            customer_bank_name_kz: customerBankNameKz
            customer_bank_name_ru: customerBankNameRu
            customer_legal_address: customerLegalAddress
            contract_number_sys: contractNumberSys
            payments_terms_ru: paymentsTermsRu
            payments_terms_kz: paymentsTermsKz
            ref_subject_type_id: refSubjectTypeId
            ref_subject_types_id: refSubjectTypesId
            is_gu: isGu
            fin_year: finYear
            ref_contract_agr_form_id: refContractAgrFormId
            ref_contract_year_type_id: refContractYearTypeId
            ref_finsource_id: refFinsourceId
            ref_currency_code: refCurrencyCode
            exchange_rate: exchangeRate
            contract_sum: contractSum
            contract_sum_wnds: contractSumWnds
            sign_date: signDate
            ec_end_date: ecEndDate
            plan_exec_date: planExecDate
            fakt_exec_date: faktExecDate
            fakt_sum: faktSum
            fakt_sum_wnds: faktSumWnds
            contract_end_date: contractEndDate
            ref_contract_cancel_id: refContractCancelId
            ref_contract_type_id: refContractTypeId
            description_kz: descriptionKz
            description_ru: descriptionRu
            fakt_trade_methods_id: faktTradeMethodsId
            ec_customer_approve: ecCustomerApprove
            ec_supplier_approve: ecSupplierApprove
            contract_ms: contractMs
            treasure_req_num: treasureReqNum
            treasure_req_date: treasureReqDate
            treasure_not_num: treasureNotNum
            treasure_not_date: treasureNotDate
            system_id: systemId
            index_date: indexDate
          }
        }